# Generated by Django 3.1 on 2021-09-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adress', models.CharField(max_length=300)),
                ('coordX', models.FloatField()),
                ('coordY', models.FloatField()),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
