# Generated by Django 3.2.4 on 2021-09-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='adress',
            new_name='address',
        ),
    ]
