# Generated by Django 3.1 on 2021-10-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_adress_hotel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
    ]
