# Generated by Django 3.1 on 2021-11-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='picture',
        ),
        migrations.AddField(
            model_name='hotel',
            name='geo_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
