# Generated by Django 3.1 on 2021-11-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20211108_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='geo_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
