# Generated by Django 3.1 on 2021-11-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20211108_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='geo_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
